config/routes.rb
Rails.application.routes.draw do
  root :to => "repository_searches#new"

  resources :repository_searches

  get "/:username/repository_issues/:id" => "repository_issues#index", :as => :repository_issues
  post "/:username/repository_issues/:id" => "repository_issues#create"
end

app/models/github_api.rb
class GithubApi
  def repositories(options)
    username = options.fetch(:username)

    get("/users/#{username}/repos")
  end

  def issues(options)
    username = options.fetch(:username)
    id       = options.fetch(:id)

    result = get("/repos/#{username}/#{id}/issues")
  end

  def create_issue(options)
    username = options.fetch(:username)
    id       = options.fetch(:id)
    title    = options.fetch(:title)

    post("/repos/#{username}/#{id}/issues", :title => title)
  end

  private

  def get(url)
    conn.get(url).body
  end

  def post(url, body)
    conn.post(url, body.to_json).body
  end

  def conn
    Faraday.new(:url => "https://api.github.com") do |faraday|
      faraday.adapter(Faraday.default_adapter)
      faraday.basic_auth(ENV["GITHUB_USERNAME"], ENV["GITHUB_PASSWORD"])
    end
  end
end

app/models/issue.rb
class Issue
  attr_accessor :title
end

app/models/repository.rb
class Repository
  def initialize(repo_hash)
    @repo_hash = repo_hash
  end

  def name
    @repo_hash["name"]
  end
end

app/models/repository_search.rb
class RepositorySearch < ActiveRecord::Base
  def repos
    JSON.parse(results).map { |result| Repository.new(result) }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/repository_issues_controller.rb
class RepositoryIssuesController < ApplicationController
  def index
    @repository_issues = JSON.parse(
      GithubApi.new.issues(:username => params[:username],
                           :id       => params[:id])
    )

    @issue = Issue.new
  end

  def create
    GithubApi.new.create_issue(:username => params[:username],
                               :id       => params[:id],
                               :title    => params[:issue][:title])

    redirect_to :action => :index
  end
end

app/controllers/repository_searches_controller.rb
class RepositorySearchesController < ApplicationController
  def new
    @repository_search = RepositorySearch.new
  end

  def show
    @repository_search = RepositorySearch.find(params[:id])
  end

  def index
    @repository_searches = RepositorySearch.all
  end

  def create
    search_results = GithubApi.new.repositories(
      :username => repository_search_params[:username]
    )

    @repository_search = RepositorySearch.new(
        repository_search_params.merge(:results => search_results)
    )

    @repository_search.save!

    redirect_to @repository_search
  end

  def repository_search_params
    params.require(:repository_search).permit(:username)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/index.html.erb
<h1>Welcome to the GitHub Explorer</h1>

<%= link_to "Find User's Repositories", new_repository_search_path, :class => "btn" %>
<%= link_to "View past searches", repository_searches_path, :class => "btn" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GithubApiExample</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav>
    <ul>
      <li>
        <%= link_to "Search", new_repository_search_path %>
      </li>
      <li>
        <%= link_to "Past Searches", repository_searches_path %>
      </li>
    </ul>
  </nav>

  <main>
    <%= yield %>
  </main>

</body>
</html>

app/views/repository_issues/index.html.erb
<h1>Create New Issue</h1>

<%= form_for @issue, :as => :issue, :url => repository_issues_path(:username => params[:username], :id => params[:id]) do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    
    <%= f.submit "Create Issue", :class => "btn" %>
<% end %>

<ul>
    <% @repository_issues.each do |issue| %>
        <li> <%= issue.fetch("title") %></li>
    <% end %>
</ul>

app/views/repository_issues/show.html.erb
<% @repository["issues"].each do |issue| %>
    <%= issue["title"] %>
<% end %>

app/views/repository_searches/index.html.erb
<h1>Past repository searches</h1>

<ul>
  <% @repository_searches.each do |repository_search| %>
    <li>
      <%= link_to repository_search.username, repository_search %>
    </li>
  <% end %>
</ul>

app/views/repository_searches/new.html.erb
<h1>Search by username:</h1>

<%= form_for @repository_search do |f| %>
    <%= f.label :username %>
    <%= f.text_field :username %>
    <%= f.submit "Search", :class => "btn" %>
<% end %>

app/views/repository_searches/show.html.erb
<h1>Repositories for <%= @repository_search.username %></h1>

<ul>
    <% @repository_search.repos.each do |repo| %>
        <li>
            <%= link_to repo.name, repository_issues_path(:username => @repository_search.username, :id => repo.name) %>
        </li>
    <% end %>
</ul>